### ISSUE TITLE
TypeError: can't pickle vtkmodules.vtkCommonDataModel.vtkPolyData objects

### ISSUE THREAD

**Issue by SLYXDWL** [laumerf/4DHeartModel#2]
When I run mva, the following error occurs :( ,

EOFError: Ran out of input
TypeError: can't pickle vtkmodules.vtkCommonDataModel.vtkPolyData objects

How can I fix it?
Thanks!

**Comment by laumerf** [comment]
Could you tell me in which file and at which line the error occurs?

**Comment by davenly1998** [comment]
The following is the error message content：

This may take a while
Traceback (most recent call last):
Traceback (most recent call last):
File"<string>",line 1,in <module>
File "run_generative_heart_model.py"，line 1389，in <module>
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\spawn.py"， line 105,  in spawn_main
exitcode = _main(fd)
File"C:\Users\fwq44\anaconda3\envs\TF2.3\limultiprocessing\spawn.py"，line 115，in _main
main()
self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
File "run_generative_heart_model.py"line 1323, in main
run_dhb_shape_ae(args，dhb_shape_configs)
File "run_generative_heart_model.py", line 176,in run_dhb_shape_ae
train dataset=data_handlergetdatasetfrom_disk("train"n train_samples)
File"D:\dwl\4DHeartModel-main\source\data.py", line 544, in get dataset_from_disk 
folder,=self._save_files_to_disk_timed_parallel(set_name, n_samples) 
File"D:\dwl\4DHeartModel-main source\data.py"line 578, in  _save_files_to_disk_timed_parallel
folder, dataset_params=self._save_files_to_disk_parallel(set_name,n_samples)
File"D:\dwl\4DHeartModel-main\source\data.py", line 703，in _save_files_to_disk_parallel
p.start()
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\process.py", line 112, in start
self._popen=self._Popen(self)
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\context.py", line 223, in _Popen 
return _default_context.get_context().Process._Popen(process_obj)
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "C:\Users\fwq44\anaconda3\envsTF2.3\lib\multiprocessing\popen_spawn_win32.py", line 89，in __init__
reduction.dump(process_obj, to_child)
File "C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\reduction.py"，line 60，in dump 
ForkingPickler(file,  protocol).dump(obj)
TypeError: can't pickle vtkmodules.vtkComm

**Comment by davenly1998** [comment]
The following is the error message content: 

This may take a while
Traceback (most recent call last):
Traceback (most recent call last):
File"<string>",line 1,in <module>
File "run_generative_heart_model.py"，line 1389，in <module>
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\spawn.py"， line 105,  in spawn_main
exitcode = _main(fd)
File"C:\Users\fwq44\anaconda3\envs\TF2.3\limultiprocessing\spawn.py"，line 115，in _main
main()
self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
File "run_generative_heart_model.py"line 1323, in main
run_dhb_shape_ae(args，dhb_shape_configs)
File "run_generative_heart_model.py", line 176,in run_dhb_shape_ae
train dataset=data_handlergetdatasetfrom_disk("train"n train_samples)
File"D:\dwl\4DHeartModel-main\source\data.py", line 544, in get dataset_from_disk 
folder,=self._save_files_to_disk_timed_parallel(set_name, n_samples) 
File"D:\dwl\4DHeartModel-main source\data.py"line 578, in  _save_files_to_disk_timed_parallel
folder, dataset_params=self._save_files_to_disk_parallel(set_name,n_samples)
File"D:\dwl\4DHeartModel-main\source\data.py", line 703，in _save_files_to_disk_parallel
p.start()
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\process.py", line 112, in start
self._popen=self._Popen(self)
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\context.py", line 223, in _Popen 
return _default_context.get_context().Process._Popen(process_obj)
File"C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "C:\Users\fwq44\anaconda3\envsTF2.3\lib\multiprocessing\popen_spawn_win32.py", line 89，in __init__
reduction.dump(process_obj, to_child)
File "C:\Users\fwq44\anaconda3\envs\TF2.3\lib\multiprocessing\reduction.py"，line 60，in dump 
ForkingPickler(file,  protocol).dump(obj)
TypeError: can't pickle vtkmodules.vtkCommonDataModel.vtkPolyData objects

**Comment by laumerf** [comment]
Is this the whole stack-trace? It's hard to pin down where exactly the error occurred. Also, the line numbers do not exactly match the ones on github.

Which python version are you using?

**Comment by davenly1998** [comment]
This error seems to be related to the use of multiprocessing in win10. I have temporarily modified the parallel operation section from the code and generated one training mesh video rather than 10(n_paralell) each time to continue running the code.
